version: "3.4"
services:
  traefik_init:
    image: traefik:1.6
    command:
      - "storeconfig"
      - "--web"
      - "--entrypoints=Name:http Address::80"
      - "--defaultentrypoints=http"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=jmaitrehenry.ca"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
    networks:
      - traefik
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - consul
  traefik:
    image: traefik:1.6
    depends_on:
      - traefik_init
      - consul
    command:
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
      - "--acme.storage=traefik/acme/account"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
      - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  consul:
    image: consul
    command: agent -server -bootstrap-expect=1
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - traefik

  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-config:/etc/odoo
      - odoo-addons:/mnt/extra-addons
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=odoo"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:odoo-ha.maartenmol.nl"
        - "traefik.docker.network=traefik_traefik"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.method=drr"
        - "traefik.port=8069"
      replicas: 1
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    networks:
      - traefik
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

networks:
  webgateway:
    driver: overlay
    external: true
  traefik:
    driver: overlay

volumes:
  odoo-web-data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.1.149,nolock,soft,rw"
      device: ":/mnt/Volume1/opslag/odoo-web-data"
  odoo-db-data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.1.149,nolock,soft,rw"
      device: ":/mnt/Volume1/opslag/odoo-db-data"
  odoo-config:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.1.149,nolock,soft,rw"
      device: ":/mnt/Volume1/opslag/odoo-config"
  odoo-addons:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.1.149,nolock,soft,rw"
      device: ":/mnt/Volume1/opslag/odoo-addons"
  consul-data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.1.149,nolock,soft,rw"
      device: ":/mnt/Volume1/opslag/consul-data"
